
4 TO - DO - Task
Please complete all the problem listed below.
4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

19

6CS012 Worksheet - 0 Siman Giri

4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

20

6CS012 Worksheet - 0 Siman Giri

4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.
3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

21

6CS012 Worksheet - 0 Siman Giri

6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

***Prompt the user to choose the type of conversion (e.g., length, weight, volume).
Ask the user to input the value to be converted.
Perform the conversion and display the result.
Handle potential errors, such as invalid input or unsupported conversion types. • Requirements:
Functions: Define at least one function to perform the conversion.
Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
User Input: Prompt the user to select the conversion type and input the value.
Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value. • Conversion Options:
Length: – Convert meters (m) to feet (ft). – Convert feet (ft) to meters (m).
Weight: – Convert kilograms (kg) to pounds (lbs). – Convert pounds (lbs) to kilograms (kg).
Volume: – Convert liters (L) to gallons (gal). – Convert gallons (gal) to liters (L).***

In [1]:
def convert_length(value, unit_from, unit_to):

    if unit_from == 'm' and unit_to == 'ft':
        return value * 3.28084
    elif unit_from == 'ft' and unit_to == 'm':
        return value / 3.28084
    else:
        raise ValueError("Invalid length conversion units.")

In [2]:
def convert_weight(value, unit_from, unit_to):
    if unit_from == 'kg' and unit_to == 'lbs':
        return value * 2.20462
    elif unit_from == 'lbs' and unit_to == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid weight conversion units.")

In [3]:
def convert_volume(value, unit_from, unit_to):
    if unit_from == 'L' and unit_to == 'gal':
        return value * 0.264172
    elif unit_from == 'gal' and unit_to == 'L':
        return value / 0.264172
    else:
        raise ValueError("Invalid volume conversion units.")


In [4]:
def main():
    try:
        conversion_type = input("Choose conversion type (length/weight/volume): ").lower()
        value = float(input("Enter the value to convert: "))

        if conversion_type == 'length':
            unit_from = input("Convert from (m/ft): ").lower()
            unit_to = input("Convert to (m/ft): ").lower()
            result = convert_length(value, unit_from, unit_to)

        elif conversion_type == 'weight':
            unit_from = input("Convert from (kg/lbs): ").lower()
            unit_to = input("Convert to (kg/lbs): ").lower()
            result = convert_weight(value, unit_from, unit_to)

        elif conversion_type == 'volume':
            unit_from = input("Convert from (L/gal): ").lower()
            unit_to = input("Convert to (L/gal): ").lower()
            result = convert_volume(value, unit_from, unit_to)

        else:
            raise ValueError("Unsupported conversion type.")

        print(f"Converted value: {result:.2f} {unit_to}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

In [5]:
main()

Error: could not convert string to float: 'confirm'


In [6]:
main()

Error: could not convert string to float: ''


In [7]:
main()

Error: could not convert string to float: ''



Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:*italicized text*

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [8]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

In [9]:
def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

In [10]:

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum value.
    """
    return max(numbers)

In [11]:

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum value.
    """
    return min(numbers)

In [12]:
def main():
    try:
        operation = input("Choose an operation (sum/average/max/min): ").lower()
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("The list of numbers cannot be empty.")

        if operation == "sum":
            result = calculate_sum(numbers)
        elif operation == "average":
            result = calculate_average(numbers)
        elif operation == "max":
            result = find_maximum(numbers)
        elif operation == "min":
            result = find_minimum(numbers)
        else:
            raise ValueError("Invalid operation selected.")

        print(f"Result: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()

Error: The list of numbers cannot be empty.


In [13]:
main()

Error: The list of numbers cannot be empty.


In [14]:
main()


Error: The list of numbers cannot be empty.


In [15]:
main()

Error: The list of numbers cannot be empty.


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

19

6CS012 Worksheet - 0 Siman Giri

4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [16]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]

In [17]:
def get_sublist(lst, start, end):
    """
    Get a sublist from start to end (inclusive).

    Parameters:
    lst (list): The input list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]

In [18]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]

In [19]:

def remove_first_last(lst):
    """
    Remove the first and last elements of a list.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The list without the first and last elements.
    """
    return lst[1:-1]

In [20]:
def get_first_n(lst, n):
    """
    Get the first n elements of a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: The first n elements of the list.
    """
    return lst[:n]

In [21]:
def get_last_n(lst, n):
    """
    Get the last n elements of a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: The last n elements of the list.
    """
    return lst[-n:]

In [22]:
def reverse_skip(lst):
    """
    Extract elements in reverse order, starting from the second-to-last element, skipping one element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The new list with elements in reverse order, skipping one element.
    """
    return lst[-2::-2]

In [23]:
def main():
    # Example usage of the functions
    lst = [1, 2, 3, 4, 5, 6]

    print("Original list:", lst)
    print("Every other element:", extract_every_other(lst))
    print("Sublist from index 2 to 4:", get_sublist(lst, 2, 4))
    print("Reversed list:", reverse_list(lst))
    print("List without first and last elements:", remove_first_last(lst))
    print("First 3 elements:", get_first_n(lst, 3))
    print("Last 2 elements:", get_last_n(lst, 2))
    print("Reverse order, skipping one element:", reverse_skip(lst))

if __name__ == "__main__":
    main()

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Sublist from index 2 to 4: [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
List without first and last elements: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse order, skipping one element: [5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.
3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

21

6CS012 Worksheet - 0 Siman Giri

6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.


In [24]:
def flatten(lst):
    """
    Flatten a nested list into a single list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

In [25]:
def access_nested_element(lst, indices):
    """
    Access a specific element in a nested list by its indices.
    """
    element = lst
    try:
        for index in indices:
            element = element[index]
        return element
    except (IndexError, TypeError):
        return "Invalid indices"

In [26]:
def sum_nested(lst):
    """
    Calculate the sum of all elements in a nested list.
    """
    return sum(flatten(lst))

In [27]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element in a nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

In [28]:
def find_max(lst):
    """
    Find the maximum element in a nested list.
    """
    return max(flatten(lst))


In [29]:
def count_occurrences(lst, elem):
    """
    Count the occurrences of an element in a nested list.
    """
    return flatten(lst).count(elem)

In [30]:
def deep_flatten(lst):
    """
    Flatten a list of lists of lists into a single list.
    """
    return flatten(lst)

In [31]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.
    """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

In [32]:

def main():
    # Example usage
    lst1 = [[1, 2], [3, 4], [5]]
    lst2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    lst3 = [[1, 2], [3, [4, 5]], 6]
    lst4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

    print("Flattened list:", flatten(lst1))
    print("Access element at [1, 2]:", access_nested_element(lst2, [1, 2]))
    print("Sum of all elements:", sum_nested(lst3))
    print("List after removing 2:", remove_element(lst1, 2))
    print("Maximum element:", find_max(lst3))
    print("Occurrences of 2:", count_occurrences(lst2, 2))
    print("Deep flattened list:", deep_flatten(lst4))
    print("Average of elements:", average_nested([[1, 2], [3, 4], [5, 6]]))

if __name__ == "__main__":
    main()

Flattened list: [1, 2, 3, 4, 5]
Access element at [1, 2]: 6
Sum of all elements: 21
List after removing 2: [[1], [3, 4], [5]]
Maximum element: 6
Occurrences of 2: 1
Deep flattened list: [1, 2, 3, 4, 5, 6, 7, 8]
Average of elements: 3.5


10 To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

46

6CS012 Worksheet - 0 Siman Giri

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [33]:
import numpy as np

In [34]:
def array_creation():
    print("1. Empty 2x2 array:")
    empty_array = np.empty((2, 2))
    print(empty_array)

    print("\n2. All ones array 4x2:")
    ones_array = np.ones((4, 2))
    print(ones_array)

    print("\n3. Array filled with 7 (shape 3x3):")
    filled_array = np.full((3, 3), 7)
    print(filled_array)

    print("\n4. Array of zeros like another array:")
    example_array = np.array([[1, 2], [3, 4]])
    zeros_like_array = np.zeros_like(example_array)
    print(zeros_like_array)

    print("\n5. Array of ones like another array:")
    ones_like_array = np.ones_like(example_array)
    print(ones_like_array)

    print("\n6. Convert list to NumPy array:")
    new_list = [1, 2, 3, 4]
    array_from_list = np.array(new_list)
    print(array_from_list)

In [35]:
def array_manipulation():
    print("\n1. Array with values from 10 to 49:")
    arr = np.arange(10, 50)
    print(arr)

    print("\n2. 3x3 matrix with values from 0 to 8:")
    matrix = np.arange(9).reshape((3, 3))
    print(matrix)

    print("\n3. 3x3 Identity matrix:")
    identity_matrix = np.eye(3)
    print(identity_matrix)

    print("\n4. Random array of size 30, mean value:")
    random_array = np.random.random(30)
    print(random_array)
    print("Mean:", random_array.mean())

    print("\n5. 10x10 random array, min and max values:")
    random_matrix = np.random.random((10, 10))
    print(random_matrix)
    print("Min:", random_matrix.min(), "Max:", random_matrix.max())

    print("\n6. Zero array with 5th element replaced by 1:")
    zero_array = np.zeros(10)
    zero_array[4] = 1
    print(zero_array)

    print("\n7. Reverse an array:")
    arr = np.array([1, 2, 0, 0, 4, 0])
    print(arr[::-1])

    print("\n8. 2D array with border 1 and inside 0:")
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    print(border_array)

    print("\n9. 8x8 checkerboard pattern:")
    checkerboard = np.zeros((8, 8))
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1
    print(checkerboard)

In [36]:
# Problem 3: Array Operations
def array_operations():
    x = np.array([[1, 2], [3, 5]])
    y = np.array([[5, 6], [7, 8]])
    v = np.array([9, 10])
    w = np.array([11, 12])

    print("\n1. Add two arrays:")
    print(x + y)

    print("\n2. Subtract two arrays:")
    print(x - y)

    print("\n3. Multiply array by 2:")
    print(x * 2)

    print("\n4. Square of each element:")
    print(np.square(x))

    print("\n5. Dot products:")
    print("v · w:", np.dot(v, w))
    print("x · v:", np.dot(x, v))
    print("x · y:\n", np.dot(x, y))

    print("\n6. Concatenate arrays:")
    print("Concatenate x and y along rows:")
    print(np.concatenate((x, y), axis=0))
    print("Concatenate v and w along columns:")
    print(np.vstack((v, w)))

    print("\n7. Try concatenating x and v (will fail):")
    try:
        print(np.concatenate((x, v), axis=0))
    except ValueError as e:
        print("Error:", e)
        print("Explanation: The shapes don't match — x is 2D, and v is 1D.")

In [37]:
# Problem 4: Matrix Operations
def matrix_operations():
    A = np.array([[3, 4], [7, 8]])
    B = np.array([[5, 3], [2, 1]])

    print("\n1. Prove A · A^-1 = I:")
    A_inv = np.linalg.inv(A)
    identity = np.dot(A, A_inv)
    print(np.round(identity, 2))

    print("\n2. Prove AB ≠ BA:")
    AB = np.dot(A, B)
    BA = np.dot(B, A)
    print("AB:\n", AB)
    print("BA:\n", BA)

    print("\n3. Prove (AB)^T = B^T · A^T:")
    AB_T = (AB).T
    BT_AT = np.dot(B.T, A.T)
    print("Transpose of AB:\n", AB_T)
    print("B^T · A^T:\n", BT_AT)

    print("\n4. Solve the system of equations:")
    # System of equations in matrix form:
    # 2x - 3y + z = -1
    # x - y + 2z = -3
    # 3x + y - z = 9

    A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
    B = np.array([-1, -3, 9])

    solution = np.linalg.solve(A, B)
    print("Solution for x, y, z:", solution)

In [38]:
def main():
    array_creation()
    array_manipulation()
    array_operations()
    matrix_operations()

if __name__ == "__main__":
    main()

1. Empty 2x2 array:
[[0. 0.]
 [0. 0.]]

2. All ones array 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (shape 3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Array of zeros like another array:
[[0 0]
 [0 0]]

5. Array of ones like another array:
[[1 1]
 [1 1]]

6. Convert list to NumPy array:
[1 2 3 4]

1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30, mean value:
[0.94660952 0.03633006 0.06057054 0.85791505 0.08432903 0.79725657
 0.65090035 0.83712254 0.54488873 0.04552287 0.43012673 0.63619394
 0.53087781 0.23625593 0.05197623 0.10357878 0.31416462 0.727952
 0.59860738 0.64875408 0.37369959 0.73247054 0.32123179 0.37630482
 0.99283736 0.92159533 0.87238739 0.03392823 0.13546654 0.58410653]
Mean: 0.482798696079

10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [39]:
import numpy as np
import time

# 1. Element-wise Addition
def element_wise_addition():
    size = 1_000_000
    list1 = list(range(size))
    list2 = list(range(size))
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python lists
    start_time = time.time()
    result_list = [x + y for x, y in zip(list1, list2)]
    end_time = time.time()
    print(f"Python list addition time: {end_time - start_time:.5f} seconds")

    # Using NumPy arrays
    start_time = time.time()
    result_array = array1 + array2
    end_time = time.time()
    print(f"NumPy array addition time: {end_time - start_time:.5f} seconds\n")

In [40]:
# 2. Element-wise Multiplication
def element_wise_multiplication():
    size = 1_000_000
    list1 = list(range(size))
    list2 = list(range(size))
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python lists
    start_time = time.time()
    result_list = [x * y for x, y in zip(list1, list2)]
    end_time = time.time()
    print(f"Python list multiplication time: {end_time - start_time:.5f} seconds")

    # Using NumPy arrays
    start_time = time.time()
    result_array = array1 * array2
    end_time = time.time()
    print(f"NumPy array multiplication time: {end_time - start_time:.5f} seconds\n")

In [41]:
# 3. Dot Product
def dot_product():
    size = 1_000_000
    list1 = list(range(size))
    list2 = list(range(size))
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python lists
    start_time = time.time()
    dot_product_list = sum(x * y for x, y in zip(list1, list2))
    end_time = time.time()
    print(f"Python list dot product time: {end_time - start_time:.5f} seconds")

    # Using NumPy arrays
    start_time = time.time()
    dot_product_array = np.dot(array1, array2)
    end_time = time.time()
    print(f"NumPy array dot product time: {end_time - start_time:.5f} seconds\n")

In [42]:
# 4. Matrix Multiplication
def matrix_multiplication():
    size = 1000
    list_matrix1 = [[i + j for j in range(size)] for i in range(size)]
    list_matrix2 = [[i * j for j in range(size)] for i in range(size)]
    array_matrix1 = np.array(list_matrix1)
    array_matrix2 = np.array(list_matrix2)

    # Using Python lists
    start_time = time.time()
    result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
    end_time = time.time()
    print(f"Python list matrix multiplication time: {end_time - start_time:.5f} seconds")

    # Using NumPy arrays
    start_time = time.time()
    result_array = np.dot(array_matrix1, array_matrix2)
    end_time = time.time()
    print(f"NumPy array matrix multiplication time: {end_time - start_time:.5f} seconds\n")

In [43]:
def main():
    print("🔵 Experiment: How Fast is NumPy? 🔵\n")
    element_wise_addition()
    element_wise_multiplication()
    dot_product()
    matrix_multiplication()

if __name__ == "__main__":
    main()


🔵 Experiment: How Fast is NumPy? 🔵

Python list addition time: 0.09336 seconds
NumPy array addition time: 0.00338 seconds

Python list multiplication time: 0.07048 seconds
NumPy array multiplication time: 0.00202 seconds

Python list dot product time: 0.07435 seconds
NumPy array dot product time: 0.00134 seconds

Python list matrix multiplication time: 80.38773 seconds
NumPy array matrix multiplication time: 0.81734 seconds

